version: '3.8'

services:
  strapi_app:
    build:
      context: .
    container_name: strapi_app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: strapi_postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - "1337:1337"
    networks:
      - strapi-net
    depends_on:
      - strapi_postgres

  strapi_postgres:
    image: postgres:15
    container_name: strapi_postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - strapi-net

  nginx:
    image: nginx:alpine
    container_name: strapi_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - strapi_app
    networks:
      - strapi-net

volumes:
  pgdata:

networks:
  strapi-net:
    external: true
